
DEFINE INPUT PARAMETER p-desafio  AS CHARACTER FORMAT "x(100)"   NO-UNDO.
DEFINE OUTPUT PARAMETER p-token   AS CHARACTER FORMAT "x(100)"  NO-UNDO.
def var x as raw.
def var y as longchar.
def var z as char.
DEFINE VARIABLE C-DESAFIO AS CHARACTER FORMAT "X(200)"      NO-UNDO.
DEFINE VARIABLE C-CHAVE   AS CHARACTER FORMAT "X(100)"      NO-UNDO.
DEFINE VARIABLE C-MDRTOTAL AS CHARACTER FORMAT "X(1000)"    NO-UNDO.
DEFINE VARIABLE C-MDRTOTAL1 AS CHARACTER FORMAT "X(1000)"   NO-UNDO. 

ASSIGN C-CHAVE = "qwertyuiopasdfgh".
       C-MDRTOTAL = C-CHAVE + p-DESAFIO + C-CHAVE.


x = md5-digest(C-MDRTOTAL).
y = hex-encode(x).
z = y.


p-token = z.


